//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSetting
    {
        public int InvoiceId { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<bool> FreeQty { get; set; }
        public Nullable<bool> ShowPreview { get; set; }
        public Nullable<bool> PrintonSave { get; set; }
        public Nullable<bool> showConfirm { get; set; }
        public string columnWidth { get; set; }
        public Nullable<int> defPrintScheme { get; set; }
        public Nullable<bool> editSaleRate { get; set; }
        public Nullable<bool> blnExtraCol { get; set; }
        public string extraColName { get; set; }
        public Nullable<int> extraColMode { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> AmtDec { get; set; }
        public string remarksCaps { get; set; }
        public string OrdDetCaps { get; set; }
        public string despDetCaps { get; set; }
        public string smsformat { get; set; }
        public string smsid { get; set; }
    }
}
