//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrAccountGroup
    {
        public long AccountGroupid { get; set; }
        public string GroupName { get; set; }
        public string BaseGroup { get; set; }
        public Nullable<bool> deActive { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
