//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrCurrency
    {
        public int id { get; set; }
        public string curName { get; set; }
        public string majorSymbol { get; set; }
        public string minorSymbol { get; set; }
        public Nullable<double> exchangeRate { get; set; }
        public Nullable<int> inwordsMode { get; set; }
        public Nullable<bool> Isdefault { get; set; }
    }
}
