//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrCommissioner
    {
        public long agentID { get; set; }
        public string agentCode { get; set; }
        public string agentName { get; set; }
        public Nullable<long> lid { get; set; }
        public string address { get; set; }
        public string contactNo { get; set; }
        public Nullable<bool> deactive { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<double> commPer { get; set; }
    }
}
