//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrCategory
    {
        public long categoryid { get; set; }
        public string category { get; set; }
        public Nullable<bool> deActive { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string regionalName { get; set; }
        public Nullable<int> McatId { get; set; }
    }
}
