//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrEmployee
    {
        public long employeeID { get; set; }
        public string employeeCode { get; set; }
        public string employeeName { get; set; }
        public Nullable<long> lid { get; set; }
        public string address { get; set; }
        public string contactNo { get; set; }
        public string gender { get; set; }
        public string bloodGroup { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<bool> deactive { get; set; }
        public Nullable<int> categoryID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<double> commPer { get; set; }
    }
}
