//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrledger
    {
        public long lid { get; set; }
        public string ledger { get; set; }
        public string LedgerName { get; set; }
        public Nullable<long> accid { get; set; }
        public string contactno { get; set; }
        public string phoneNo { get; set; }
        public string address { get; set; }
        public string tinno { get; set; }
        public Nullable<long> areaid { get; set; }
        public Nullable<bool> deActive { get; set; }
        public Nullable<int> plID { get; set; }
        public string email { get; set; }
        public Nullable<int> loyaltyID { get; set; }
        public string regionalName { get; set; }
        public string remarks { get; set; }
        public Nullable<double> DiscPer { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<double> creditlimit { get; set; }
        public Nullable<int> posid { get; set; }
        public string stateCode { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> CustTypeID { get; set; }
        public Nullable<int> CreditDays { get; set; }
    }
}
