//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrplaceofSupply
    {
        public long Id { get; set; }
        public string placeName { get; set; }
        public Nullable<bool> deActive { get; set; }
        public Nullable<int> rorder { get; set; }
    }
}
