//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrProduct
    {
        public long prodID { get; set; }
        public string prodCode { get; set; }
        public string prodName { get; set; }
        public long categoryid { get; set; }
        public Nullable<decimal> gstPer { get; set; }
        public Nullable<decimal> igstPer { get; set; }
        public Nullable<bool> staxincl { get; set; }
        public Nullable<bool> ptaxincl { get; set; }
        public string mnf { get; set; }
        public string mainUnit { get; set; }
        public string Rack { get; set; }
        public Nullable<decimal> prate { get; set; }
        public Nullable<decimal> srate { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<double> cessPer { get; set; }
        public Nullable<double> rol { get; set; }
        public string remarks { get; set; }
        public Nullable<double> prateper { get; set; }
        public Nullable<double> srateper { get; set; }
        public string regionalName { get; set; }
        public Nullable<bool> blnExpiry { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string alternateUnit { get; set; }
        public Nullable<double> convfactor { get; set; }
        public Nullable<int> itemClassID { get; set; }
        public string Batch { get; set; }
        public string hsnCode { get; set; }
        public Nullable<bool> IsBoardItem { get; set; }
        public string pluCode { get; set; }
        public Nullable<double> AddCess { get; set; }
        public Nullable<double> OSRate { get; set; }
        public string outerBatch { get; set; }
        public Nullable<double> SPComPer { get; set; }
        public Nullable<bool> Inclusive1 { get; set; }
        public Nullable<bool> Inclusive2 { get; set; }
        public Nullable<bool> Inclusive3 { get; set; }
        public Nullable<double> rate1 { get; set; }
        public Nullable<double> rate2 { get; set; }
        public Nullable<double> rate3 { get; set; }
        public Nullable<double> taxPer1 { get; set; }
        public Nullable<double> taxPer2 { get; set; }
        public Nullable<double> taxPer3 { get; set; }
        public string SplitPrinter { get; set; }
        public Nullable<double> kfcessPer { get; set; }
        public Nullable<double> AgentComPer { get; set; }
        public Nullable<double> LoyaltyPoint { get; set; }
        public Nullable<int> IsMultiTax { get; set; }
        public Nullable<long> mcategoryid { get; set; }
        public Nullable<double> mrpper { get; set; }
        public Nullable<double> OSMrp { get; set; }
        public Nullable<double> DiscPer { get; set; }
    }
}
