//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrRolePermission
    {
        public int roleId { get; set; }
        public string screenName { get; set; }
        public Nullable<bool> isread { get; set; }
        public Nullable<bool> isadd { get; set; }
        public Nullable<bool> isedit { get; set; }
        public Nullable<bool> iscancel { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<bool> isprint { get; set; }
        public Nullable<bool> isexport { get; set; }
        public Nullable<bool> isemail { get; set; }
        public Nullable<bool> issms { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<bool> isreedit { get; set; }
        public Nullable<bool> isauthenticate { get; set; }
    }
}
