//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrTable
    {
        public int Id { get; set; }
        public string tableName { get; set; }
        public int ccid { get; set; }
        public int chairCount { get; set; }
        public Nullable<int> plid { get; set; }
        public Nullable<bool> deActive { get; set; }
        public Nullable<bool> IsAc { get; set; }
    }
}
