//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintSetting
    {
        public int Id { get; set; }
        public string InvoiceType { get; set; }
        public string SchemeName { get; set; }
        public Nullable<bool> DosMode { get; set; }
        public Nullable<int> paperWidth { get; set; }
        public Nullable<int> Leftmargin { get; set; }
        public Nullable<int> paperFeed { get; set; }
        public Nullable<int> reverseFeed { get; set; }
        public Nullable<int> footerLines { get; set; }
        public Nullable<int> fontIndex { get; set; }
        public Nullable<int> fontSizeIndex { get; set; }
        public Nullable<int> Nooflines { get; set; }
        public Nullable<bool> blnVarlines { get; set; }
        public Nullable<bool> blnNormal { get; set; }
        public string printer { get; set; }
        public string blnprintValues { get; set; }
        public string gridColHeadWidth { get; set; }
        public string printtextvalues { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
