//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsAgeing
    {
        public int Id { get; set; }
        public long lid { get; set; }
        public long invid { get; set; }
        public string invtype { get; set; }
        public string invNo { get; set; }
        public Nullable<System.DateTime> invDate { get; set; }
        public Nullable<double> drAmount { get; set; }
        public Nullable<double> crAmount { get; set; }
        public Nullable<double> billAmount { get; set; }
        public Nullable<double> balAmount { get; set; }
        public Nullable<bool> IsSettle { get; set; }
    }
}
