//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsAttandance
    {
        public Nullable<double> AttID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> TotAmount { get; set; }
        public Nullable<int> Advance { get; set; }
        public Nullable<int> Incentive { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
