//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsBOMDetail
    {
        public int bomId { get; set; }
        public long prodID { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<int> rOrder { get; set; }
        public Nullable<int> bomMode { get; set; }
        public Nullable<bool> blnAltUnit { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
