//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsBOM
    {
        public int bomId { get; set; }
        public string bomName { get; set; }
        public string description { get; set; }
        public Nullable<bool> deActive { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
