//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsCustLoyality
    {
        public Nullable<int> Lid { get; set; }
        public Nullable<int> LoyId { get; set; }
        public Nullable<double> PointIn { get; set; }
        public Nullable<double> Pointout { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
