//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsloyalty
    {
        public long SaleID { get; set; }
        public int loyaltyID { get; set; }
        public int LID { get; set; }
        public Nullable<double> saleAmount { get; set; }
        public Nullable<double> PointIn { get; set; }
        public Nullable<double> PointOut { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string invtype { get; set; }
        public Nullable<int> invid { get; set; }
    }
}
