//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsOTP
    {
        public long otpId { get; set; }
        public string mobileno { get; set; }
        public string type { get; set; }
        public string otpCode { get; set; }
        public System.DateTime expiryDate { get; set; }
    }
}
