//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsStockQty
    {
        public Nullable<long> ItemID { get; set; }
        public string Batch { get; set; }
        public Nullable<double> Prate { get; set; }
        public Nullable<double> SRate { get; set; }
        public Nullable<double> Mrp { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<long> intBatch { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<bool> deActive { get; set; }
        public string expDate { get; set; }
        public Nullable<int> ccid { get; set; }
    }
}
