//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsSale
    {
        public long invid { get; set; }
        public string invType { get; set; }
        public string invno { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public string party { get; set; }
        public Nullable<long> lid { get; set; }
        public string mop { get; set; }
        public string taxType { get; set; }
        public string contactno { get; set; }
        public string remarks { get; set; }
        public string address { get; set; }
        public Nullable<int> SalePersonID { get; set; }
        public Nullable<decimal> grossAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> taxableAmount { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> Exempted { get; set; }
        public Nullable<decimal> roundOff { get; set; }
        public Nullable<decimal> cashDiscount { get; set; }
        public Nullable<decimal> billAmount { get; set; }
        public Nullable<int> roundOffMode { get; set; }
        public Nullable<double> otherExpense { get; set; }
        public Nullable<double> freightCoolie { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> saleValues { get; set; }
        public Nullable<double> BillProfit { get; set; }
        public Nullable<bool> blnOrder { get; set; }
        public string OrderID { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<int> loyID { get; set; }
        public Nullable<double> pointIn { get; set; }
        public Nullable<double> pointOut { get; set; }
        public string cardNo { get; set; }
        public string cardExpMnth { get; set; }
        public string cardExpyr { get; set; }
        public string cardcvNo { get; set; }
        public string tinNo { get; set; }
        public string cardName { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<long> AutoNo { get; set; }
        public string compName { get; set; }
        public Nullable<long> userid { get; set; }
        public string OrderDetail { get; set; }
        public string DespatchDetail { get; set; }
        public Nullable<double> cessAmount { get; set; }
        public Nullable<double> AddCessAmt { get; set; }
        public Nullable<int> rndCutoff { get; set; }
        public Nullable<double> creditAmount { get; set; }
        public Nullable<double> cashAmount { get; set; }
        public Nullable<double> cardAmount { get; set; }
        public Nullable<double> itemDiscount { get; set; }
        public Nullable<int> ccID { get; set; }
        public string ccName { get; set; }
        public string cardDetails { get; set; }
        public Nullable<bool> blnProcessed { get; set; }
        public Nullable<double> costfactor { get; set; }
        public string referenceNo { get; set; }
        public Nullable<double> labourCost { get; set; }
        public Nullable<double> otherCost { get; set; }
        public Nullable<double> serviceTax { get; set; }
        public Nullable<double> cessOnTax { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> counterid { get; set; }
        public Nullable<bool> IsSettled { get; set; }
        public Nullable<int> dccID { get; set; }
        public string dccName { get; set; }
        public Nullable<double> cgstAmount { get; set; }
        public Nullable<double> sgstAmount { get; set; }
        public Nullable<double> igstAmount { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<double> kfcessAmt { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<long> ReturnId { get; set; }
        public Nullable<System.DateTime> CreditDate { get; set; }
        public string CreditStatus { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> TcsPer { get; set; }
        public Nullable<double> TcsAmt { get; set; }
        public Nullable<double> AgentAmt { get; set; }
        public Nullable<int> AgentLid { get; set; }
        public Nullable<double> SaveAmt { get; set; }
        public Nullable<double> TotMrp { get; set; }
        public string GRNNo { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
    }
}
