//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsStockJournaldetail
    {
        public Nullable<long> invid { get; set; }
        public Nullable<long> itemid { get; set; }
        public Nullable<double> taxper { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> freeQty { get; set; }
        public Nullable<decimal> grossAmount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> taxable { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> netAmount { get; set; }
        public string Batch { get; set; }
        public Nullable<double> sRate { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> saleValue { get; set; }
        public Nullable<double> profit { get; set; }
        public string productionid { get; set; }
        public Nullable<int> rOrder { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<double> unitfactor { get; set; }
        public Nullable<bool> blnAltUnit { get; set; }
        public string expDate { get; set; }
        public string unit { get; set; }
        public string extraColumn { get; set; }
        public Nullable<double> pRate { get; set; }
        public string modifier { get; set; }
        public Nullable<double> cgstPer { get; set; }
        public Nullable<double> cgstAmount { get; set; }
        public Nullable<double> sgstPer { get; set; }
        public Nullable<double> sgstAmount { get; set; }
        public Nullable<double> igstPer { get; set; }
        public Nullable<double> igstAmount { get; set; }
        public Nullable<double> cessPer { get; set; }
        public Nullable<double> cessAmount { get; set; }
        public Nullable<double> AddCessRate { get; set; }
        public Nullable<double> AddCessAmt { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string SerialNo { get; set; }
        public Nullable<double> kfcessper { get; set; }
        public Nullable<double> kfcessamt { get; set; }
        public Nullable<double> AgentPer { get; set; }
        public Nullable<double> AgentAmt { get; set; }
    }
}
