//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsStock
    {
        public Nullable<long> Invid { get; set; }
        public string InvType { get; set; }
        public Nullable<System.DateTime> Invdate { get; set; }
        public Nullable<long> itemid { get; set; }
        public Nullable<double> qtyin { get; set; }
        public Nullable<double> qtyout { get; set; }
        public string Batch { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> sRate { get; set; }
        public Nullable<double> pRate { get; set; }
        public Nullable<int> lid { get; set; }
        public string invNo { get; set; }
        public Nullable<int> ccid { get; set; }
        public Nullable<double> cost { get; set; }
    }
}
