//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsUserlog
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string screenName { get; set; }
        public string actionType { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public Nullable<System.DateTime> logTime { get; set; }
        public string remarks { get; set; }
    }
}
