//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsVoucher
    {
        public Nullable<long> InvID { get; set; }
        public long invno { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public string vchtype { get; set; }
        public Nullable<int> drLID { get; set; }
        public Nullable<int> crLID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string refNo { get; set; }
        public string remarks { get; set; }
        public string issueingBank { get; set; }
        public string chequeNo { get; set; }
        public Nullable<int> spID { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<double> crAmount { get; set; }
        public string narration { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<bool> IsReconcil { get; set; }
        public string CheqStatus { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<System.DateTime> ReconcilDate { get; set; }
        public string compName { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<double> taxable { get; set; }
        public Nullable<double> taxAmt { get; set; }
        public Nullable<double> taxPer { get; set; }
        public Nullable<int> lid { get; set; }
        public string taxRefNo { get; set; }
        public Nullable<int> rMode { get; set; }
        public Nullable<int> ccid { get; set; }
        public string ccName { get; set; }
        public Nullable<long> agentid { get; set; }
    }
}
