//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaMobiConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<companySetting> companySettings { get; set; }
        public virtual DbSet<InvoiceSetting> InvoiceSettings { get; set; }
        public virtual DbSet<mtrAccountGroup> mtrAccountGroups { get; set; }
        public virtual DbSet<mtrArea> mtrAreas { get; set; }
        public virtual DbSet<mtrCategory> mtrCategories { get; set; }
        public virtual DbSet<mtrCommissioner> mtrCommissioners { get; set; }
        public virtual DbSet<mtrCostCentre> mtrCostCentres { get; set; }
        public virtual DbSet<mtrCounter> mtrCounters { get; set; }
        public virtual DbSet<mtrCurrency> mtrCurrencies { get; set; }
        public virtual DbSet<mtrEmployee> mtrEmployees { get; set; }
        public virtual DbSet<mtrItemImage> mtrItemImages { get; set; }
        public virtual DbSet<mtrledger> mtrledgers { get; set; }
        public virtual DbSet<mtrloyalty> mtrloyalties { get; set; }
        public virtual DbSet<mtrManufacturer> mtrManufacturers { get; set; }
        public virtual DbSet<mtrModifier> mtrModifiers { get; set; }
        public virtual DbSet<mtrplaceofSupply> mtrplaceofSupplies { get; set; }
        public virtual DbSet<mtrPricelist> mtrPricelists { get; set; }
        public virtual DbSet<mtrProduct> mtrProducts { get; set; }
        public virtual DbSet<mtrRole> mtrRoles { get; set; }
        public virtual DbSet<mtrTable> mtrTables { get; set; }
        public virtual DbSet<mtrUser> mtrUsers { get; set; }
        public virtual DbSet<PrintSetting> PrintSettings { get; set; }
        public virtual DbSet<trsBOM> trsBOMs { get; set; }
        public virtual DbSet<trsloyalty> trsloyalties { get; set; }
        public virtual DbSet<trsOrder> trsOrders { get; set; }
        public virtual DbSet<trsOTP> trsOTPs { get; set; }
        public virtual DbSet<trsPurchase> trsPurchases { get; set; }
        public virtual DbSet<trsSale> trsSales { get; set; }
        public virtual DbSet<trsStockJournal> trsStockJournals { get; set; }
        public virtual DbSet<mtrRolePermission> mtrRolePermissions { get; set; }
        public virtual DbSet<trsAgeing> trsAgeings { get; set; }
        public virtual DbSet<trsAttandance> trsAttandances { get; set; }
        public virtual DbSet<trsBOMDetail> trsBOMDetails { get; set; }
        public virtual DbSet<trsCustLoyality> trsCustLoyalities { get; set; }
        public virtual DbSet<trsItemOffer> trsItemOffers { get; set; }
        public virtual DbSet<trsOrderDetail> trsOrderDetails { get; set; }
        public virtual DbSet<trsPricelist> trsPricelists { get; set; }
        public virtual DbSet<trsPurchasedetail> trsPurchasedetails { get; set; }
        public virtual DbSet<trsSalaryPay> trsSalaryPays { get; set; }
        public virtual DbSet<trsSaledetail> trsSaledetails { get; set; }
        public virtual DbSet<trsStock> trsStocks { get; set; }
        public virtual DbSet<trsStockJournaldetail> trsStockJournaldetails { get; set; }
        public virtual DbSet<trsStockQty> trsStockQties { get; set; }
        public virtual DbSet<trsUserlog> trsUserlogs { get; set; }
        public virtual DbSet<trsVoidItem> trsVoidItems { get; set; }
        public virtual DbSet<trsVoucher> trsVouchers { get; set; }
    }
}
